config/routes.rb
Rcms::Application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get '*url', to: 'pages#show'
  root 'index#index'

  

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < InheritedResources::Base
  def show
    @page = Page.find_by_url(params[:url]) || not_found
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/index/index.html.erb
<h1>Index#index</h1>
<p>Find me in app/views/index/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rcms</title>
  <%= stylesheet_link_tag    "application", media: "all"%>
  <%= javascript_include_tag "application"%>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.title %></td>
        <td><%= page.url %></td>
        <td><%= page.content %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
p <%= @page.content %>